### ISSUE TITLE
Why do we preserve the google_appengine subdirectory in this repo?

### ISSUE THREAD

**Issue by ajessup** [GoogleCloudPlatform/appengine-wordpress-plugin#1]
It seems redundant, and also means that to install the plugin from the latest in the repo, they need to (a) download a ZIP of the recent project, (b) extract it, (c) create a new archive of the contents of google_appengine/*, (d) try installing into Wordpress.

Removing this subdirectory would eliminate most of these steps (user would just download the zip of the master branch from github and then import straight into WordPress)

**Comment by tmatsuo** [comment]
The plugin is in WordPress repo. Is it still relevant?
