### ISSUE TITLE
Image slider can't access images from cloud storage

### ISSUE THREAD

**Issue by perqa** [GoogleCloudPlatform/appengine-wordpress-plugin#11]
My Wordpress setup works perfectly on my local machine, with an image slider that scales and crops images to fit the full width of the browser window. This does not seem to work on App Engine with images on Cloud Storage. The slider images don't show up at all on the site. I'm using the Customizr theme slider.

All slider images get invalid URLs, like this one:

Failed to load resource: the server responded with a status of 404 (Not Found) http://lh3.ggpht.com/dQWB2UTfQKJMkQIqFBG1TL3PbgYq4GKvf88HjZdbrQQXObIGtz4rTmVkD_vfEk6EXXIm0yOGmzy2UtQv5kw3YCU4f0g-98WUrQ=s99999-c

The invalid URLs seem to be generated by the appengine-wordpress-plugin, because disabling it results in normal URLs (still invalid, though). The bad URLs only occur in context of the image slider.

After some more investigation, I have found that the theme logic sets slider width to 99999 to indicate full-width (which is not unusual). If I modify that width to a value like 9990, I get valid URLs, the images display, but they are incorrectly cropped and scaled. It would be great with a proper solution to this problem.
From wp-content/themes/customizr/inc/class-fire-init.php:
`$this -> slider_full_size = array('width' => 99999 , 'height' => 500, 'crop' => true );`

**Comment by tmatsuo** [comment]
I think this is an issue with that theme, so closing for now, but feel free to reopen if you think differently.
