### ISSUE TITLE
Images should be loaded over https if page is hosted on https

### ISSUE THREAD

**Issue by perqa** [GoogleCloudPlatform/appengine-wordpress-plugin#12]
Image URLs created by appengine-wordpress-plugin are insecure http, even though the page is hosted on https.

Example:
`The page at 'https://wp-dot-xxx-yyy-123.appspot.com/' was loaded over HTTPS, 
but displayed insecure content from 'http://lh4.ggpht.com/7SVmfoMBnl1kQ1su2cWZZTYQbO9KDzeuWql2TPvbnEdAS8T3N9OmUz1fv86Fws9OhoTc_7MEWjpa8MNubBHOxIJrWk4m4_NH=s99999-c': 
this content should also be loaded over HTTPS.`

**Comment by CezarisLT** [comment]
Did you fix this? I having the same problem. I uploaded over 200 assets and the load true http, ONLY, i need them to load true https. Thank.

**Comment by tmatsuo** [comment]
@Kivylius I think you need to rewrite the entries in the wordpress db.

Here is the support case about such issues:
https://wordpress.org/support/topic/how-to-update-older-image-urls/

Some of the plugins can do the rewrite.
