### ISSUE TITLE
WP 3.9 Issues

### ISSUE THREAD

**Issue by richardroyal** [GoogleCloudPlatform/appengine-wordpress-plugin#14]
I'm having an issue with the plugin and the latest WordPress, 3.9.

I think a few others are having a similar experience:

https://wordpress.org/support/topic/activating-plug-in-gives-blank-page?replies=6#post-5523668

With the plugin activated, I just get a white screen.

Either:
1. We're missing something.
2. The sites we tried to install had some other issue conflicting with the plugin.

or
1. The current WordPress is not compatible with GAE.

Can you guys help us out? Thanks

**Comment by tmatsuo** [comment]
The topic in your comment seems resolved, so closing for now. Please reopen if you still have this issue.
