### ISSUE TITLE
Plugin clearing GCS bucket on activation?

### ISSUE THREAD

**Issue by Trii** [GoogleCloudPlatform/appengine-wordpress-plugin#19]
I haven't been able to track it down yet but it seems like the GCS bucket is being cleared out at some point if you activate/deactivate/reactivate the plugin

**Comment by tmatsuo** [comment]
Cleaning up the old issues. Please re-open if it's still relevant

**Comment by Trii** [comment]
This was over two years ago, and I have since stopped using WordPress on GCE. Unfortunately I can neither confirm nor deny it happening any longer. Hopefully if it is, someone will come across this ticket and reopen it. If not, then all's well 😄
