### ISSUE TITLE
php55 runtime issues

### ISSUE THREAD

**Issue by joshuarubin** [GoogleCloudPlatform/appengine-wordpress-plugin#23]
With the php55 runtime, when this plugin exists (not even enabled), all pages are getting errors like this in the logs:

```
PHP Fatal error:  Cannot use object of type __PHP_Incomplete_Class as array in <appengine_dir>/wordpress/wp-includes/post.php on line 2092
PHP Fatal error:  Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0
```

Sometimes the first loaded page will work, but then other pages will not.

Switching back to the php runtime makes things work again.
Also, while using the php55 runtime, removing this plugin also gets things working.

Note that I've tried with all other plugins disabled as well.

Using wordpress 4.1.1

**Comment by sjlangley** [comment]
Just tried 4.2.2 and no errors, before that I had 4.1 which also worked find.

Googling "__PHP_Incomplete_Class" suggests it's a deserialization problem - perhaps you had something stored in a session and clearing memcache might fix it up.
