### ISSUE TITLE
Error when activated

### ISSUE THREAD

**Issue by thegronix** [GoogleCloudPlatform/appengine-wordpress-plugin#24]
When I try to activate this plugin GAE 1.6, I receive error:

Warning: require_once(google/appengine/api/urlfetch_service_pb.php): failed to open stream: No such file or directory in
/wp-content/plugins/google-app-engine/modules/urlfetch.php on line 72

Fatal error: require_once(): Failed opening required 'google/appengine/api/urlfetch_service_pb.php' (include_path='.:/usr/local/php5.4/lib/php') in
/wp-content/plugins/google-app-engine/modules/urlfetch.php on line 72
<\blockquote>

How to resolve this ?
I use WP 4.1.1

**Comment by sjlangley** [comment]
It doesn't look like you're running the plugin on App Engine, either in the development server or the production server.
