### ISSUE TITLE
memcached plugin abandonware warning

### ISSUE THREAD

**Issue by nikmartin** [GoogleCloudPlatform/appengine-wordpress-plugin#28]
The recommended memcached plugin: https://wordpress.org/plugins/memcached/ has a warning: 

> This plugin hasn't been updated in over 2 years. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

**Comment by rask** [comment]
That plugin/dropin has been tested and seems to work just fine in GAE and on regular servers.
